version: '3.7'
services:
    api:
        build: 
            context: ./api
            dockerfile: Dockerfile
            args:
                API_ENV: ${API_ENV}
        volumes:
            - ./api:/usr/app/
            - ./shared:/usr/app/shared/
            - /usr/app/.cache/
            - /usr/app/node_modules/
        ports:
            - "${API_PORT}:${API_PORT}"
        environment:
            NODE_ENV: 'local'
            CHOKIDAR_USEPOLLING: 1
        tty: true

    _status:
        depends_on: 
            - api