version: '3.7'
services:
    db:
        build: 
            context: ./db
            dockerfile: Dockerfile
        restart: always
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: 0
            MYSQL_USER: admin
            MYSQL_PASSWORD: admin
            MYSQL_ROOT_PASSWORD: superAdmin
            MYSQL_DATABASE: default
            CHOKIDAR_USEPOLLING: 1
        tty: true
        volumes:
            - ./db:/db/
            - ./shared:/db/shared
        ports:
            - "${DB_PORT}:3306"

    _status:
        depends_on: 
            - db