version: '3.7'
services:
    web:
        build: 
            context: ./web
            dockerfile: Dockerfile
            args:
                WEB_ENV: "${WEB_ENV}"
        volumes:
            - ./web:/usr/app/
            - ./shared:/usr/app/shared/
            - /usr/app/.cache/
            - /usr/app/node_modules/
        ports:
            - "${WEB_PORT}:${WEB_PORT}"
            - "${WEB_HMR_PORT}:${WEB_HMR_PORT}"
        environment:
            NODE_ENV: 'local'
            CHOKIDAR_USEPOLLING: 1
        tty: true

    _status:
        depends_on: 
            - web