version: '3.7'
services:
    web:
        # build from custom Dockerfile
        build: 
            context: ./web
            dockerfile: Dockerfile
        volumes:
            - ./web:/usr/app/
            - /usr/app/.cache
        ports:
            - "${WEB_PORT}:${WEB_PORT}"
            - "${WEB_HMR_PORT}:${WEB_HMR_PORT}"
        environment:
            NODE_ENV: 'local'
            CHOKIDAR_USEPOLLING: 1
