version: '3.7'
services:
    web:
        build: 
            context: ./_status
            dockerfile: ../Dockerfile.dummy

    api:
        build: 
            context: ./_status
            dockerfile: ../Dockerfile.dummy

    db: 
        build: 
            context: ./_status
            dockerfile: ../Dockerfile.dummy

    _status:
        build: 
            context: ./_status
            dockerfile: Dockerfile
        volumes:
            - ./_status:/usr/app/
            - /usr/app/.cache/
            - /usr/app/node_modules/
        environment:
            NODE_ENV: 'local'
            CHOKIDAR_USEPOLLING: 1
        tty: true